[package]
name = "rpci"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["nix", "nom", "thiserror"]

[dependencies]
libc = "0.2"
nix = { version = "0.26", optional = true }
nom = { version = "7", optional = true }
thiserror = { version = "1", optional = true }
